export default [
  {
    userId: 1,
    name: 'Link',
    battleName: 'hero0',
    classes: 'red-boy',
    str: 20,
    def: 16,
    exp: 0,
    maxMp: 30,
    currentMp: 30,
    maxHp: 350,
    currentHp: 150,
    accuracy: 10,
    magic: 10,
    evade: 6,
    agility: 11,
    currentPositionX: 13,
    currentPositionY: 3,
    id: 1,
    inPlay: true,
    killed: false,
    attackerId: 'hero1'
  },
  {
    userId: 1,
    name: 'Ellie',
    battleName: 'hero1',
    classes: 'white-girl',
    magicAbilities: [
      'Cure1',
      'Fire1',
      'Lightning1'
    ],
    magic: 19,
    str: 11,
    def: 10,
    exp: 0,
    maxMp: 50,
    currentMp: 50,
    maxHp: 219,
    currentHp: 219,
    accuracy: 8,
    evade: 6,
    agility: 9,
    id: 2,
    inPlay: true,
    killed: false,
    attackerId: 'hero2'
  },
  {
    userId: 1,
    name: 'Luke',
    battleName: 'hero2',
    classes: 'green-boy',
    magicAbilities: [
      'Cure1',
      'Fire1',
      'Lightning1'
    ],
    magic: 19,
    str: 11,
    def: 10,
    exp: 0,
    maxMp: 50,
    currentMp: 50,
    maxHp: 219,
    currentHp: 219,
    accuracy: 8,
    evade: 6,
    agility: 13,
    id: 3,
    inPlay: true,
    killed: false,
    attackerId: 'hero3'
  }
];
